language: csharp
mono: none
dotnet: 3.1.100
solution: JsonApiDotNetCore.MongoDb.sln
services:
  - mongodb
script:
  - dotnet restore
  - dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=lcov /p:CoverletOutput=./coverage/lcov-coverage
after_success:
  - bash <(curl -s https://codecov.io/bash)
before_deploy:
  - dotnet build -c Release
  - dotnet pack -c Release
deploy:
  skip_cleanup: true
  provider: script
  script: dotnet nuget push ./src/JsonApiDotNetCore.MongoDb/bin/Release/JsonApiDotNetCore.MongoDb.*.nupkg -k $NUGET_API -s https://api.nuget.org/v3/index.json
  on:
    branch: master
