language: csharp
mono: none
dotnet: 3.1.100
solution: JsonApiDotNetCore.MongoDb.sln
services:
  - mongodb
before_script:
  - sleep 15
script:
  - dotnet restore
  - dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=lcov /p:CoverletOutput=./coverage/lcov-coverage
after_success:
  - bash <(curl -s https://codecov.io/bash)
