@hostAddress = https://localhost:44340

### Gets all high-priority todo-items.

GET {{hostAddress}}/api/todoItems?filter=equals(priority,'High')

### Creates a todo-item.

POST {{hostAddress}}/api/todoItems
Content-Type: application/vnd.api+json

{
  "data": {
    "type": "todoItems",
    "attributes": {
      "description": "Review open issues",
      "priority": "High",
      "durationInHours": 1
    }
  }
}

### Creates multiple todo-items.

POST {{hostAddress}}/api/operations
Accept: application/vnd.api+json; ext="https://jsonapi.org/ext/atomic"
Content-Type: application/vnd.api+json; ext="https://jsonapi.org/ext/atomic"

{
  "atomic:operations": [
    {
      "op": "add",
      "data": {
        "type": "todoItems",
        "attributes": {
          "description": "Create release",
          "priority": "High",
          "durationInHours": 1
        }
      }
    },
    {
      "op": "add",
      "data": {
        "type": "todoItems",
        "attributes": {
          "description": "Add release notes",
          "priority": "High",
          "durationInHours": 2
        }
      }
    }
  ]
}
